### ISSUE TITLE
Halite reset method does not randomize the board any more

### ISSUE THREAD

**Issue by honglu2875** [Kaggle/kaggle-environments#63] opened 2020-07-24 22:28 UTC
As the title suggested, the reset() method in Halite environment no longer randomize the board. The code I tried are very simple lines (with necessary libraries imported of course):
`env = make('halite')`
`env.reset(4)`
And when I repeatedly run `env.reset(4)`, I always get the same board. I know clearly it wasn't the case a few weeks ago. Is this change of behavior intentional? If I repeatedly run both lines, it certainly generates a randomized board because the whole environment object is brand new. But I have a lot of codes based on the assumption that the initial state of the board is not fixed for a given kaggle environment object. 

I'm aware that there is a recent change on certain codes regarding random seeds, but I do not have time to fully digest the source code yet.

This is pretty important for me because I'm working on RL  and my training calls reset() every time expecting a different and randomized board. My training of models has been performing really wierd recently and I found out about this too late. This sudden change of reset() behavior just destroyed all my training works in the previous weeks. The fix is easy, but please enlighten me what actually happened. Perhaps the earlier behavior of randomizing the board was a bug? Or did you change its design recently?

**Comment by harrisse** [comment] 2020-07-28 23:32
Yes, this change was caused by the random seed introduction. I have not tested this but you should be able to call `env.configuration.randomSeed = None` after reset to get a new random board.  
  
The reason this happens is because seed is part of the environment configuration and configuration doesn't get cleared for a particular environment between runs unless you explicitly clear it. This has historically been undefined behavior since we didn't have seeds. If others feel strongly at this point I am open to reconsidering the behavior, but in general I am comfortable with how seeds work today.

**Comment by bovard** [comment] 2022-04-01 20:51
Closing this as halite is over

**Closed by bovard** 2022-04-01 20:51 UTC
